name: Pull Request

on:
  pull_request:
    types: [opened, ready_for_review, reopened, synchronize]

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Install PNPM
        uses: pnpm/action-setup@v4
        with:
          version: 9
      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'
      - name: Install Dependencies
        run: pnpm install
  checks:
    runs-on: ubuntu-latest
    needs: setup
    strategy:
      matrix:
        script: ['lint', 'test', 'type-check']
    steps:
      - name: ${{ matrix.script }}
        run: pnpm run ${{ matrix.script }}
