name: Pull Request

on:
  pull_request:
    types: [opened, ready_for_review, reopened, synchronize]

jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Install PNPM
        uses: pnpm/action-setup@v4
        with:
          run_install: false
          version: 9
      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'
      - name: Install Dependencies
        run: pnpm install
      - name: Changeset
        run: pnpm changeset status --since=main
      - name: Lint
        run: pnpm run lint
      - name: Test
        run: pnpm run test
      - name: Type Check
        run: pnpm run type-check
